pipeline:
  identifier: Build_react_starter_1696238040368
  name: Build react-starter
  orgIdentifier: default
  projectIdentifier: Dhairya
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1696238024689
        repoName: react-starter
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
